[CmdletBinding()]
param(
    [ValidateSet('Apply', 'Summary', 'Reset', 'Validate', 'TestTargets', 'Restart')]
    [string]$Mode = 'Apply',
    [string]$Root = (Split-Path -Parent $PSScriptRoot)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$corePath = Join-Path $PSScriptRoot 'nexroute-services-core.ps1'
$definitionPath = Join-Path $PSScriptRoot 'services.json'
$statePath = Join-Path $PSScriptRoot 'services-state.json'
$runtimePath = Join-Path $PSScriptRoot 'services-runtime.cmd'

if (-not (Test-Path -LiteralPath $corePath -PathType Leaf)) {
    throw "NexRoute service-matrix core is missing: $corePath"
}

function Get-NexRouteDefinitions {
    return @((Get-Content -LiteralPath $definitionPath -Raw -Encoding UTF8 | ConvertFrom-Json).services)
}

function Get-NexRouteState {
    param([array]$Definitions)
    $state = [ordered]@{}
    foreach ($service in $Definitions) { $state[$service.id] = [bool]$service.defaultEnabled }
    if (Test-Path -LiteralPath $statePath -PathType Leaf) {
        try {
            $saved = Get-Content -LiteralPath $statePath -Raw -Encoding UTF8 | ConvertFrom-Json
            foreach ($service in $Definitions) {
                $property = $saved.PSObject.Properties[$service.id]
                if ($null -ne $property) { $state[$service.id] = [bool]$property.Value }
            }
        }
        catch { }
    }
    return $state
}

function Get-NexRoutePortText {
    param([string[]]$Values)
    $ports = @($Values | Where-Object { $_ } | ForEach-Object { ([string]$_).Trim() } | Where-Object { $_ -match '^\d+(?:-\d+)?$' } | Sort-Object -Unique)
    if ($ports.Count -eq 0) { return '65535' }
    return ($ports -join ',')
}

function Write-NexRouteRuntime {
    $definitions = Get-NexRouteDefinitions
    $state = Get-NexRouteState -Definitions $definitions
    $tcpPorts = New-Object 'System.Collections.Generic.List[string]'
    $udpPorts = New-Object 'System.Collections.Generic.List[string]'
    $enabled = 0

    foreach ($service in $definitions) {
        if (-not [bool]$state[$service.id]) { continue }
        $enabled++
        foreach ($port in @($service.tcpPorts)) { if ($port) { $tcpPorts.Add([string]$port) } }
        foreach ($port in @($service.udpPorts)) { if ($port) { $udpPorts.Add([string]$port) } }
    }

    $tcpText = Get-NexRoutePortText -Values $tcpPorts.ToArray()
    $udpText = Get-NexRoutePortText -Values $udpPorts.ToArray()
    $lists = Join-Path $Root 'lists'
    $bin = Join-Path $Root 'bin'
    $hostList = Join-Path $lists 'list-services-enabled.txt'
    $ipset = Join-Path $lists 'ipset-services-user.txt'
    $tlsPattern = Join-Path $bin 'tls_clienthello_4pda_to.bin'
    $quicPattern = Join-Path $bin 'quic_initial_www_google_com.bin'

    $tcpByName = '--filter-tcp={0} --hostlist="{1}" --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern="{2}" --new' -f $tcpText, $hostList, $tlsPattern
    $tcpByIp = '--filter-tcp={0} --ipset="{1}" --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern="{2}" --new' -f $tcpText, $ipset, $tlsPattern
    $udpByName = '--filter-udp={0} --hostlist="{1}" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic="{2}" --new' -f $udpText, $hostList, $quicPattern
    $udpByIp = '--filter-udp={0} --ipset="{1}" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic="{2}" --new' -f $udpText, $ipset, $quicPattern

    $lines = @(
        '@echo off',
        'rem Generated by NexRoute 0.2.2 Service Matrix. Do not edit.',
        ('set "NEXROUTE_ENABLED_SERVICE_COUNT={0}"' -f $enabled),
        ('set "NEXROUTE_EXTRA_TCP_PORTS={0}"' -f $tcpText),
        ('set "NEXROUTE_EXTRA_UDP_PORTS={0}"' -f $udpText),
        ('set "NEXROUTE_SERVICE_TCP_ARGS={0} {1}"' -f $tcpByName, $tcpByIp),
        ('set "NEXROUTE_SERVICE_UDP_ARGS={0} {1}"' -f $udpByName, $udpByIp)
    )
    [System.IO.File]::WriteAllLines($runtimePath, $lines, [System.Text.Encoding]::ASCII)
}

if ($Mode -in @('Apply', 'Reset')) {
    $output = @(& $corePath -Mode $Mode -Root $Root)
    Write-NexRouteRuntime
    $output | ForEach-Object { Write-Output $_ }
    exit 0
}

# PowerShell script invocation does not set $LASTEXITCODE. With
# ErrorActionPreference=Stop, any core failure is already terminating.
& $corePath -Mode $Mode -Root $Root
exit 0
