# Internal NexRoute Service Matrix module. Dot-sourced by nexroute-services.ps1.

function Get-SafeServiceId {
    param([Parameter(Mandatory)][string]$Value)
    $safe = $Value.ToLowerInvariant() -replace '[^a-z0-9_-]', '-'
    if ([string]::IsNullOrWhiteSpace($safe)) { throw "Invalid service id: $Value" }
    return $safe
}

function Write-ServiceRuntime {
    param([Parameter(Mandatory)][AllowEmptyCollection()][array]$RuntimeServices)

    $bin = Join-Path $Root 'bin'
    $tlsPattern = Join-Path $bin 'tls_clienthello_4pda_to.bin'
    $quicPattern = Join-Path $bin 'quic_initial_www_google_com.bin'
    $tcpBlocks = New-Object 'System.Collections.Generic.List[string]'
    $udpBlocks = New-Object 'System.Collections.Generic.List[string]'
    $allTcpPorts = New-Object 'System.Collections.Generic.List[string]'
    $allUdpPorts = New-Object 'System.Collections.Generic.List[string]'

    foreach ($item in $RuntimeServices) {
        $tcpText = Get-PortText -Ports @($item.TcpPorts) -Fallback ''
        $udpText = Get-PortText -Ports @($item.UdpPorts) -Fallback ''
        foreach ($port in @($item.TcpPorts)) { if ($port) { $allTcpPorts.Add([string]$port) } }
        foreach ($port in @($item.UdpPorts)) { if ($port) { $allUdpPorts.Add([string]$port) } }

        if ($tcpText) {
            if ([bool]$item.HasDomains) {
                $tcpBlocks.Add(('--filter-tcp={0} --hostlist="{1}" --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern="{2}" --new' -f $tcpText, $item.HostList, $tlsPattern))
            }
            if ([bool]$item.HasIps) {
                $tcpBlocks.Add(('--filter-tcp={0} --ipset="{1}" --dpi-desync=multisplit --dpi-desync-split-seqovl=568 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern="{2}" --new' -f $tcpText, $item.IpSet, $tlsPattern))
            }
        }

        if ($udpText) {
            if ([bool]$item.HasDomains) {
                $udpBlocks.Add(('--filter-udp={0} --hostlist="{1}" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic="{2}" --new' -f $udpText, $item.HostList, $quicPattern))
            }
            if ([bool]$item.HasIps) {
                $udpBlocks.Add(('--filter-udp={0} --ipset="{1}" --dpi-desync=fake --dpi-desync-repeats=8 --dpi-desync-fake-quic="{2}" --new' -f $udpText, $item.IpSet, $quicPattern))
            }
        }
    }

    $tcpArgs = if ($tcpBlocks.Count -gt 0) { $tcpBlocks.ToArray() -join ' ' } else { '--filter-tcp=65535 --hostlist="' + $enabledListPath + '" --new' }
    $udpArgs = if ($udpBlocks.Count -gt 0) { $udpBlocks.ToArray() -join ' ' } else { '--filter-udp=65535 --hostlist="' + $enabledListPath + '" --new' }
    $lines = @(
        '@echo off',
        'rem Generated by NexRoute 0.2.3 Service Matrix. Do not edit.',
        ('set "NEXROUTE_ENABLED_SERVICE_COUNT={0}"' -f $RuntimeServices.Count),
        ('set "NEXROUTE_EXTRA_TCP_PORTS={0}"' -f (Get-PortText -Ports $allTcpPorts.ToArray())),
        ('set "NEXROUTE_EXTRA_UDP_PORTS={0}"' -f (Get-PortText -Ports $allUdpPorts.ToArray())),
        ('set "NEXROUTE_SERVICE_TCP_ARGS={0}"' -f $tcpArgs),
        ('set "NEXROUTE_SERVICE_UDP_ARGS={0}"' -f $udpArgs)
    )
    [System.IO.File]::WriteAllLines($runtimePath, $lines, [System.Text.Encoding]::ASCII)
}

function Remove-StaleServiceLists {
    param([Parameter(Mandatory)][AllowEmptyCollection()][string[]]$KeepPaths)
    if (-not (Test-Path -LiteralPath $listsDirectory -PathType Container)) { return }
    foreach ($file in @(Get-ChildItem -LiteralPath $listsDirectory -File -ErrorAction SilentlyContinue | Where-Object { $_.Name -match '^(list|ipset)-service-[a-z0-9_-]+\.txt$' })) {
        if ($KeepPaths -notcontains $file.FullName) { Remove-Item -LiteralPath $file.FullName -Force -ErrorAction SilentlyContinue }
    }
}

function Apply-ServiceMatrix {
    param([Parameter(Mandatory)][array]$Definitions, [Parameter(Mandatory)]$State)

    $enabledDomains = New-Object 'System.Collections.Generic.HashSet[string]'
    $allDomains = New-Object 'System.Collections.Generic.HashSet[string]'
    $enabledIds = New-Object 'System.Collections.Generic.List[string]'
    $runtimeServices = New-Object 'System.Collections.Generic.List[object]'
    $allIps = New-Object 'System.Collections.Generic.HashSet[string]'
    $allSourceStatuses = New-Object 'System.Collections.Generic.List[object]'
    $keepPaths = New-Object 'System.Collections.Generic.List[string]'

    foreach ($service in $Definitions) {
        foreach ($domainValue in @($service.domains)) {
            if ([string]::IsNullOrWhiteSpace([string]$domainValue)) { continue }
            $domain = ([string]$domainValue).Trim().ToLowerInvariant()
            [void]$allDomains.Add($domain)
            if ([bool]$State[$service.id]) { [void]$enabledDomains.Add($domain) }
        }
    }

    $disabledDomains = [string[]]@($allDomains | Where-Object { -not $enabledDomains.Contains($_) } | Sort-Object)
    $enabledDomainArray = [string[]]@($enabledDomains | Sort-Object)
    Set-ManagedBlock -Path $generalUserPath -BeginMarker $generalBegin -EndMarker $generalEnd -Values $enabledDomainArray
    Set-ManagedBlock -Path $excludeUserPath -BeginMarker $excludeBegin -EndMarker $excludeEnd -Values $disabledDomains

    $enabledValues = $enabledDomainArray
    if ($enabledValues.Count -eq 0) { $enabledValues = @('nexroute.invalid') }
    Write-Utf8NoBom -Path $enabledListPath -Content (($enabledValues -join "`r`n") + "`r`n")

    foreach ($service in $Definitions) {
        if (-not [bool]$State[$service.id]) { continue }
        $id = Get-SafeServiceId -Value ([string]$service.id)
        $enabledIds.Add($id)

        $serviceDomains = [string[]]@($service.domains | Where-Object { $_ } | ForEach-Object { ([string]$_).Trim().ToLowerInvariant() } | Sort-Object -Unique)
        $hostListPath = Join-Path $listsDirectory ("list-service-{0}.txt" -f $id)
        $ipsetPath = Join-Path $listsDirectory ("ipset-service-{0}.txt" -f $id)
        $keepPaths.Add($hostListPath)
        $keepPaths.Add($ipsetPath)
        $hostValues = if ($serviceDomains.Count -gt 0) { $serviceDomains } else { @('nexroute.invalid') }
        Write-Utf8NoBom -Path $hostListPath -Content (($hostValues -join "`r`n") + "`r`n")

        $ips = New-Object 'System.Collections.Generic.HashSet[string]'
        foreach ($entryValue in @($service.ipCidrs)) {
            $entry = ConvertTo-ValidatedIpCidr -Value ([string]$entryValue)
            if ($entry) { [void]$ips.Add($entry) }
        }

        $remote = Get-RemoteIpEntries -Sources @($service.ipSources)
        foreach ($entry in [string[]]$remote.Entries) { [void]$ips.Add($entry) }
        foreach ($status in [object[]]$remote.Statuses) {
            $allSourceStatuses.Add([pscustomobject]@{
                serviceId = $id
                source = $status.source
                status = $status.status
                count = $status.count
                cacheAgeDays = $status.cacheAgeDays
                message = $status.message
            })
        }

        $resolveHosts = New-Object 'System.Collections.Generic.List[string]'
        foreach ($hostName in @($service.resolveHosts)) { if ($hostName) { $resolveHosts.Add([string]$hostName) } }
        foreach ($target in @($service.testTargets)) {
            $hostName = Get-EndpointHost -Target $target
            if ($hostName) { $resolveHosts.Add($hostName) }
        }
        foreach ($entry in @(Get-ResolvedIpEntries -Hosts $resolveHosts.ToArray())) { [void]$ips.Add($entry) }

        $ipValues = [string[]]@($ips | Sort-Object)
        $hasIps = $ipValues.Count -gt 0
        if (-not $hasIps) { $ipValues = @('203.0.113.113/32') }
        Write-Utf8NoBom -Path $ipsetPath -Content (($ipValues -join "`r`n") + "`r`n")
        foreach ($entry in [string[]]@($ips | ForEach-Object { $_ })) { [void]$allIps.Add($entry) }

        $runtimeServices.Add([pscustomobject]@{
            Id = $id
            HostList = $hostListPath
            IpSet = $ipsetPath
            HasDomains = ($serviceDomains.Count -gt 0)
            HasIps = $hasIps
            TcpPorts = @($service.tcpPorts)
            UdpPorts = @($service.udpPorts)
        })
    }

    Remove-StaleServiceLists -KeepPaths $keepPaths.ToArray()
    $globalIps = [string[]]@($allIps | Sort-Object)
    if ($globalIps.Count -eq 0) { $globalIps = @('203.0.113.113/32') }
    Write-Utf8NoBom -Path $serviceIpsetPath -Content (($globalIps -join "`r`n") + "`r`n")
    Write-JsonFile -Path $sourceStatusPath -Value ([object[]]$allSourceStatuses.ToArray()) -Depth 6
    Write-ServiceRuntime -RuntimeServices $runtimeServices.ToArray()

    return [pscustomobject]@{
        Enabled = $enabledIds.Count
        EnabledIds = $enabledIds.ToArray()
        Domains = $enabledDomains.Count
        DisabledDomains = $disabledDomains.Count
        ResolvedIps = $globalIps.Count
        RuntimeGroups = $runtimeServices.Count
        SourceStatuses = $allSourceStatuses.Count
    }
}
